server:
  port: 0

spring:

flightsApi:
  url:${URL_FLIGHTS:http://flight-service}

dolarapi:
  url: ${URL_DOLAR:https://dolarapi.com/v1/dolares/tarjeta}

eureka:
  instance:
    prefer-ip-address: true
  client:
    #Que quiero que se registre y me traiga ese registro
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
